src/Presentation/Nop.Web/Areas/Admin/Controllers/RecurringPaymentController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Services.Localization;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Web.Areas.Admin.Factories;
using Nop.Web.Areas.Admin.Models.Orders;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Web.Areas.Admin.Controllers
{
    public partial class RecurringPaymentController : BaseAdminController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly IOrderService _orderService;
        private readonly IPermissionService _permissionService;
        private readonly IRecurringPaymentModelFactory _recurringPaymentModelFactory;

        #endregion Fields

        #region Ctor

        public RecurringPaymentController(ILocalizationService localizationService,
            IOrderProcessingService orderProcessingService,
            IOrderService orderService,
            IPermissionService permissionService,
            IRecurringPaymentModelFactory recurringPaymentModelFactory)
        {
            this._localizationService = localizationService;
            this._orderProcessingService = orderProcessingService;
            this._orderService = orderService;
            this._permissionService = permissionService;
            this._recurringPaymentModelFactory = recurringPaymentModelFactory;
        }

        #endregion

        #region Methods

        public virtual IActionResult Index()
        {
            return RedirectToAction("List");
        }

        public virtual IActionResult List()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentSearchModel(new RecurringPaymentSearchModel());

            return View(model);
        }

        [HttpPost]
        public virtual IActionResult List(RecurringPaymentSearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedKendoGridJson();

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentListModel(searchModel);

            return Json(model);
        }

        public virtual IActionResult Edit(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null || payment.Deleted)
                return RedirectToAction("List");

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

            return View(model);
        }

        [HttpPost, ParameterBasedOnFormName("save-continue", "continueEditing")]
        [FormValueRequired("save", "save-continue")]
        public virtual IActionResult Edit(RecurringPaymentModel model, bool continueEditing)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(model.Id);
            if (payment == null || payment.Deleted)
                return RedirectToAction("List");

            if (ModelState.IsValid)
            {
                payment.CycleLength = model.CycleLength;
                payment.CyclePeriodId = model.CyclePeriodId;
                payment.TotalCycles = model.TotalCycles;
                payment.IsActive = model.IsActive;
                _orderService.UpdateRecurringPayment(payment);

                SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.Updated"));

                if (!continueEditing)
                    return RedirectToAction("List");

                //selected tab
                SaveSelectedTabName();

                return RedirectToAction("Edit", new { id = payment.Id });
            }

            //prepare model
            model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(model, payment, true);

            //if we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public virtual IActionResult Delete(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null)
                return RedirectToAction("List");

            _orderService.DeleteRecurringPayment(payment);

            SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.Deleted"));

            return RedirectToAction("List");
        }

        [HttpPost]
        public virtual IActionResult HistoryList(RecurringPaymentHistorySearchModel searchModel)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedKendoGridJson();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(searchModel.RecurringPaymentId)
                ?? throw new ArgumentException("No recurring payment found with the specified id");

            //prepare model
            var model = _recurringPaymentModelFactory.PrepareRecurringPaymentHistoryListModel(searchModel, payment);

            return Json(model);
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("processnextpayment")]
        public virtual IActionResult ProcessNextPayment(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null)
                return RedirectToAction("List");

            try
            {
                var errors = _orderProcessingService.ProcessNextRecurringPayment(payment).ToList();
                if (errors.Any())
                    errors.ForEach(error => ErrorNotification(error, false));
                else
                    SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.NextPaymentProcessed"), false);

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected tab
                SaveSelectedTabName(persistForTheNextRequest: false);

                return View(model);
            }
            catch (Exception exc)
            {
                ErrorNotification(exc, false);

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected tab
                SaveSelectedTabName(persistForTheNextRequest: false);

                return View(model);
            }
        }

        [HttpPost, ActionName("Edit")]
        [FormValueRequired("cancelpayment")]
        public virtual IActionResult CancelRecurringPayment(int id)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageRecurringPayments))
                return AccessDeniedView();

            //try to get a recurring payment with the specified id
            var payment = _orderService.GetRecurringPaymentById(id);
            if (payment == null)
                return RedirectToAction("List");

            try
            {
                var errors = _orderProcessingService.CancelRecurringPayment(payment);
                if (errors.Any())
                {
                    foreach (var error in errors)
                        ErrorNotification(error, false);
                }
                else
                    SuccessNotification(_localizationService.GetResource("Admin.RecurringPayments.Cancelled"), false);

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected tab
                SaveSelectedTabName(persistForTheNextRequest: false);

                return View(model);
            }
            catch (Exception exc)
            {
                ErrorNotification(exc, false);

                //prepare model
                var model = _recurringPaymentModelFactory.PrepareRecurringPaymentModel(null, payment);

                //selected tab
                SaveSelectedTabName(persistForTheNextRequest: false);

                return View(model);
            }
        }

        #endregion
    }
}

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/Edit.cshtml
@model RecurringPaymentModel

@{
    //page title
    ViewBag.Title = T("Admin.RecurringPayments.EditPaymentDetails").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Recurring payments");
}

<form asp-controller="RecurringPayment" asp-action="Edit" method="post">
    <div class="content-header clearfix">
        <h1 class="pull-left">
            @T("Admin.RecurringPayments.EditPaymentDetails")
            <small>
                <i class="fa fa-arrow-circle-left"></i>
                <a asp-action="List">@T("Admin.RecurringPayments.BackToList")</a>
            </small>
        </h1>
        <div class="pull-right">
            <button type="submit" name="save" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.Save")
            </button>
            <button type="submit" name="save-continue" class="btn bg-blue">
                <i class="fa fa-floppy-o"></i>
                @T("Admin.Common.SaveContinue")
            </button>
            <span id="payment-delete" class="btn bg-red">
                <i class="fa fa-trash-o"></i>
                @T("Admin.Common.Delete")
            </span>
            @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailsButtons, additionalData = Model })
        </div>
    </div>
    @await Html.PartialAsync("_CreateOrUpdate", Model)
</form>
<nop-delete-confirmation asp-model-id="@Model.Id" asp-button-id="payment-delete" />

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/List.cshtml
@model RecurringPaymentSearchModel

@{
    //page title
    ViewBag.Title = T("Admin.RecurringPayments").Text;
    //active menu item (system name)
    Html.SetActiveMenuItemSystemName("Recurring payments");
}

<nop-antiforgery-token />
<div class="content-header clearfix">
    <h1 class="pull-left">
        @T("Admin.RecurringPayments")
    </h1>
    <div class="pull-right">
        &nbsp;
        @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentListButtons })
    </div>
</div>

<div class="content">
    <div class="form-horizontal">
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-body">
                    <p>
                        @T("Admin.RecurringPayments.Description")
                    </p>
                    <div id="recurringpayments-grid"></div>

                    <script>
                        $(document).ready(function() {
                            $("#recurringpayments-grid").kendoGrid({
                                dataSource: {
                                    type: "json",
                                    transport: {
                                        read: {
                                            url: "@Html.Raw(Url.Action("List", "RecurringPayment"))",
                                            type: "POST",
                                            dataType: "json",
                                            data: addAntiForgeryToken
                                        }
                                    },
                                    schema: {
                                        data: "Data",
                                        total: "Total",
                                        errors: "Errors"
                                    },
                                    error: function(e) {
                                        display_kendoui_grid_error(e);
                                        // Cancel the changes
                                        this.cancelChanges();
                                    },
                                    pageSize: @(Model.PageSize),
                                    serverPaging: true,
                                    serverFiltering: true,
                                    serverSorting: true
                                },
                                pageable: {
                                    refresh: true,
                                    pageSizes: [@(Model.AvailablePageSizes)],
                                    @await Html.PartialAsync("_GridPagerMessages")
                                },
                                editable: {
                                    confirmation: "@T("Admin.Common.DeleteConfirmation")",
                                    mode: "inline"
                                },
                                scrollable: false,
                                columns: [
                                    {
                                        field: "Id",
                                        title: "@T("Admin.RecurringPayments.Fields.ID")",
                                        width: 50
                                    }, {
                                        field: "CustomerId",
                                        title: "@T("Admin.RecurringPayments.Fields.Customer")",
                                        width: 200,
                                        template: '<a href="@Url.Content("~/Admin/Customer/Edit/")#=CustomerId#">#:CustomerEmail#</a>'
                                    }, {
                                        field: "CycleLength",
                                        title: "@T("Admin.RecurringPayments.Fields.CycleLength")",
                                        width: 100
                                    }, {
                                        field: "CyclePeriodStr",
                                        title: "@T("Admin.RecurringPayments.Fields.CyclePeriod")",
                                        width: 100
                                    }, {
                                        field: "IsActive",
                                        title: "@T("Admin.RecurringPayments.Fields.IsActive")",
                                        width: 100,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        template: '# if(IsActive) {# <i class="fa fa-check true-icon"></i> #} else {# <i class="fa fa-close false-icon"></i> #} #'
                                    }, {
                                        field: "StartDate",
                                        title: "@T("Admin.RecurringPayments.Fields.StartDate")",
                                        width: 200,
                                        type: "date",
                                        format: "{0:G}"
                                    }, {
                                        field: "NextPaymentDate",
                                        title: "@T("Admin.RecurringPayments.Fields.NextPaymentDate")",
                                        width: 200,
                                        type: "date",
                                        format: "{0:G}"
                                    }, {
                                        field: "TotalCycles",
                                        title: "@T("Admin.RecurringPayments.Fields.TotalCycles")",
                                        width: 100
                                    }, {
                                        field: "CyclesRemaining",
                                        title: "@T("Admin.RecurringPayments.Fields.CyclesRemaining")",
                                        width: 100
                                    }, {
                                        field: "Id",
                                        title: "@T("Admin.Common.Edit")",
                                        width: 100,
                                        headerAttributes: { style: "text-align:center" },
                                        attributes: { style: "text-align:center" },
                                        template: '<a class="btn btn-default" href="Edit/#=Id#"><i class="fa fa-pencil"></i>@T("Admin.Common.Edit")</a>'                                    }
                                ]
                            });
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.History.cshtml
@model RecurringPaymentModel

<div class="panel-group">
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailsHistoryTop, additionalData = Model })
    <div class="panel panel-default">
        <div class="panel-body">
            @if (Model.LastPaymentFailed)
            {
                <div class="form-group">
                    <div class="col-md-12">
                        @T("Admin.RecurringPayments.History.LastPaymentFailed")
                    </div>
                </div>
            }
            @if (!string.IsNullOrEmpty(Model.NextPaymentDate))
            {
                <div class="form-group">
                    <div class="col-md-12">
                        @T("Admin.RecurringPayments.History.NextPaymentDate")
                        <text>:</text>
                        @Model.NextPaymentDate
                    </div>
                </div>
            }
            @if (!string.IsNullOrEmpty(Model.NextPaymentDate) || Model.CanCancelRecurringPayment)
            {
                <div class="form-group">
                    <div class="col-md-12">
                        @if (!string.IsNullOrEmpty(Model.NextPaymentDate))
                        {
                            <button type="submit" name="processnextpayment" class="btn bg-green">
                                @T("Admin.RecurringPayments.History.ProcessNextPayment")
                            </button>
                        }
                        @if (Model.CanCancelRecurringPayment)
                        {
                            <button type="submit" name="cancelpayment" class="btn bg-navy">
                                @T("Admin.RecurringPayments.History.CancelPayment")
                            </button>
                        }
                    </div>
                </div>
            }

            <div id="history-grid"></div>

            <script>
                $(document).ready(function () {
                    $("#history-grid").kendoGrid({
                        dataSource: {
                            type: "json",
                            transport: {
                                read: {
                                    url: "@Html.Raw(Url.Action("HistoryList", "RecurringPayment"))",
                                    type: "POST",
                                    dataType: "json",
                                    data: function() {
                                        var data = {
                                            RecurringPaymentId: '@(Model.Id)'
                                        };
                                        addAntiForgeryToken(data);
                                        return data;
                                    }
                                }
                            },
                            schema: {
                                data: "Data",
                                total: "Total",
                                errors: "Errors"
                            },
                            error: function (e) {
                                display_kendoui_grid_error(e);
                                // Cancel the changes
                                this.cancelChanges();
                            },
                            pageSize: @(Model.RecurringPaymentHistorySearchModel.PageSize),
                            serverPaging: true,
                            serverFiltering: true,
                            serverSorting: true
                        },
                        pageable: {
                            refresh: true,
                            pageSizes: [@(Model.RecurringPaymentHistorySearchModel.AvailablePageSizes)],
                            @await Html.PartialAsync("_GridPagerMessages")
                        },
                        editable: {
                            confirmation: "@T("Admin.Common.DeleteConfirmation")",
                            mode: "inline"
                        },
                        scrollable: false,
                        columns: [
                            {
                                field: "CustomOrderNumber",
                                title: "@T("Admin.RecurringPayments.History.CustomOrderNumber")",
                                width: 200,
                                headerAttributes: { style: "text-align:center" },
                                attributes: { style: "text-align:center" },
                                template: '<a class="btn btn-default" href="@Url.Content("~/Admin/Order/Edit/")#=OrderId#"><i class="fa fa-eye"></i>#=CustomOrderNumber# - @T("Admin.Common.View")</a>'
                            }, {
                                field: "OrderStatus",
                                title: "@T("Admin.RecurringPayments.History.OrderStatus")",
                                width: 200
                            }, {
                                field: "PaymentStatus",
                                title: "@T("Admin.RecurringPayments.History.PaymentStatus")",
                                width: 200
                            }, {
                                field: "ShippingStatus",
                                title: "@T("Admin.RecurringPayments.History.ShippingStatus")",
                                width: 200
                            }, {
                                field: "CreatedOn",
                                title: "@T("Admin.RecurringPayments.History.CreatedOn")",
                                width: 200,
                                type: "date",
                                format: "{0:G}"
                            }
                        ]
                    });
                });
            </script>
        </div>
    </div>
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailsHistoryBottom, additionalData = Model })
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.Info.cshtml
@using Nop.Core.Domain.Catalog
@using Nop.Services
@model RecurringPaymentModel

<div class="panel-group">
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailsInfoTop, additionalData = Model })
    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="InitialOrderId" />
                </div>
                <div class="col-md-9">
                    <a asp-controller="Order" asp-action="Edit" asp-route-id="@Model.InitialOrderId">@T("Admin.Common.View")</a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="CustomerEmail" />
                </div>
                <div class="col-md-9">
                    <a asp-controller="Customer" asp-action="Edit" asp-route-id="@Model.CustomerId">@Model.CustomerEmail</a>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="CycleLength" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="CycleLength" />
                    <span asp-validation-for="CycleLength"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="CyclePeriodId" />
                </div>
                <div class="col-md-9">
                    <nop-select asp-for="CyclePeriodId" asp-items="@(((RecurringProductCyclePeriod)Model.CyclePeriodId).ToSelectList())" />
                    <span asp-validation-for="CyclePeriodId"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="TotalCycles" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="TotalCycles" />
                    <span asp-validation-for="TotalCycles"></span>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="CyclesRemaining" />
                </div>
                <div class="col-md-9">
                    <div class="form-text-row">@Model.CyclesRemaining</div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="PaymentType" />
                </div>
                <div class="col-md-9">
                    <div class="form-text-row">@Model.PaymentType</div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="StartDate" />
                </div>
                <div class="col-md-9">
                    <div class="form-text-row">@Model.StartDate</div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-3">
                    <nop-label asp-for="IsActive" />
                </div>
                <div class="col-md-9">
                    <nop-editor asp-for="IsActive" />
                    <span asp-validation-for="IsActive"></span>
                </div>
            </div>
        </div>
    </div>
    @await Component.InvokeAsync("AdminWidget", new { widgetZone = AdminWidgetZones.ReccuringPaymentDetailsInfoBottom, additionalData = Model })
</div>

src/Presentation/Nop.Web/Areas/Admin/Views/RecurringPayment/_CreateOrUpdate.cshtml
@model RecurringPaymentModel

@inject IEventPublisher eventPublisher

<div asp-validation-summary="All"></div>
<input asp-for="Id" type="hidden" />

<div class="content">
    <div class="form-horizontal">
        <nop-tabs id="recurringpayment-edit">
            <nop-tab asp-name="tab-info" asp-default="true" asp-title="@T("Admin.RecurringPayments.Info")">@await Html.PartialAsync("_CreateOrUpdate.Info", Model)</nop-tab>
            <nop-tab asp-name="tab-history" asp-title="@T("Admin.RecurringPayments.History")">@await Html.PartialAsync("_CreateOrUpdate.History", Model)</nop-tab>
        </nop-tabs>
    </div>
</div>

@{
    //custom tabs
    var eventMessage = new AdminTabStripCreated(this.Html, "recurringpayment-edit");
    eventPublisher.Publish(eventMessage);
    foreach (var eventBlock in eventMessage.BlocksToRender)
    {
        @eventBlock
    }
}