src/Plugins/Nop.Plugin.Shipping.UPS/Controllers/ShippingUPSController.cs
using System;
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Nop.Core;
using Nop.Plugin.Shipping.UPS.Domain;
using Nop.Plugin.Shipping.UPS.Models;
using Nop.Services;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Security;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;

namespace Nop.Plugin.Shipping.UPS.Controllers
{
    [AuthorizeAdmin]
    [Area(AreaNames.Admin)]
    public class ShippingUPSController : BasePluginController
    {
        #region Fields

        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly ISettingService _settingService;
        private readonly UPSSettings _upsSettings;

        #endregion

        #region Ctor

        public ShippingUPSController(ILocalizationService localizationService,
            IPermissionService permissionService,
            ISettingService settingService,
            UPSSettings upsSettings)
        {
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._settingService = settingService;
            this._upsSettings = upsSettings;
        }

        #endregion

        #region Methods

        public IActionResult Configure()
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            var model = new UPSShippingModel
            {
                Url = _upsSettings.Url,
                AccountNumber = _upsSettings.AccountNumber,
                AccessKey = _upsSettings.AccessKey,
                Username = _upsSettings.Username,
                Password = _upsSettings.Password,
                AdditionalHandlingCharge = _upsSettings.AdditionalHandlingCharge,
                InsurePackage = _upsSettings.InsurePackage,
                PackingPackageVolume = _upsSettings.PackingPackageVolume,
                PackingType = (int)_upsSettings.PackingType,
                PackingTypeValues = _upsSettings.PackingType.ToSelectList(),
                PassDimensions = _upsSettings.PassDimensions
            };
            foreach (UPSCustomerClassification customerClassification in Enum.GetValues(typeof(UPSCustomerClassification)))
            {
                model.AvailableCustomerClassifications.Add(new SelectListItem
                {
                    Text = CommonHelper.ConvertEnum(customerClassification.ToString()),
                    Value = customerClassification.ToString(),
                    Selected = customerClassification == _upsSettings.CustomerClassification
                });
            }
            foreach (UPSPickupType pickupType in Enum.GetValues(typeof(UPSPickupType)))
            {
                model.AvailablePickupTypes.Add(new SelectListItem
                {
                    Text = CommonHelper.ConvertEnum(pickupType.ToString()),
                    Value = pickupType.ToString(),
                    Selected = pickupType == _upsSettings.PickupType
                });
            }
            foreach (UPSPackagingType packagingType in Enum.GetValues(typeof(UPSPackagingType)))
            {
                model.AvailablePackagingTypes.Add(new SelectListItem
                {
                    Text = CommonHelper.ConvertEnum(packagingType.ToString()),
                    Value = packagingType.ToString(),
                    Selected = packagingType == _upsSettings.PackagingType
                });
            }

            // Load Domestic service names
            var carrierServicesOfferedDomestic = _upsSettings.CarrierServicesOffered;
            foreach (var service in UPSServices.Services)
                model.AvailableCarrierServices.Add(service);

            if (!string.IsNullOrEmpty(carrierServicesOfferedDomestic))
                foreach (var service in UPSServices.Services)
                {
                    var serviceId = UPSServices.GetServiceId(service);
                    if (!string.IsNullOrEmpty(serviceId))
                    {
                        // Add delimiters [] so that single digit IDs aren't found in multi-digit IDs
                        if (carrierServicesOfferedDomestic.Contains($"[{serviceId}]"))
                            model.CarrierServicesOffered.Add(service);
                    }
                }

            return View("~/Plugins/Shipping.UPS/Views/Configure.cshtml", model);
        }

        [HttpPost]
        [AdminAntiForgery]
        public IActionResult Configure(UPSShippingModel model)
        {
            if (!_permissionService.Authorize(StandardPermissionProvider.ManageShippingSettings))
                return AccessDeniedView();

            if (!ModelState.IsValid)
                return Configure();

            //save settings
            _upsSettings.Url = model.Url;
            _upsSettings.AccountNumber = model.AccountNumber;
            _upsSettings.AccessKey = model.AccessKey;
            _upsSettings.Username = model.Username;
            _upsSettings.Password = model.Password;
            _upsSettings.AdditionalHandlingCharge = model.AdditionalHandlingCharge;
            _upsSettings.InsurePackage = model.InsurePackage;
            _upsSettings.CustomerClassification = (UPSCustomerClassification)Enum.Parse(typeof(UPSCustomerClassification), model.CustomerClassification);
            _upsSettings.PickupType = (UPSPickupType)Enum.Parse(typeof(UPSPickupType), model.PickupType);
            _upsSettings.PackagingType = (UPSPackagingType)Enum.Parse(typeof(UPSPackagingType), model.PackagingType);
            _upsSettings.PackingPackageVolume = model.PackingPackageVolume;
            _upsSettings.PackingType = (PackingType)model.PackingType;
            _upsSettings.PassDimensions = model.PassDimensions;
            _upsSettings.Tracing = model.Tracing;


            // Save selected services
            var carrierServicesOfferedDomestic = new StringBuilder();
            var carrierServicesDomesticSelectedCount = 0;
            if (model.CheckedCarrierServices != null)
            {
                foreach (var cs in model.CheckedCarrierServices)
                {
                    carrierServicesDomesticSelectedCount++;
                    var serviceId = UPSServices.GetServiceId(cs);
                    if (!string.IsNullOrEmpty(serviceId))
                    {
                        // Add delimiters [] so that single digit IDs aren't found in multi-digit IDs
                        carrierServicesOfferedDomestic.AppendFormat("[{0}]:", serviceId);
                    }
                }
            }
            // Add default options if no services were selected
            if (carrierServicesDomesticSelectedCount == 0)
                _upsSettings.CarrierServicesOffered = "[03]:[12]:[11]:[08]:";
            else
                _upsSettings.CarrierServicesOffered = carrierServicesOfferedDomestic.ToString();

            _settingService.SaveSetting(_upsSettings);

            SuccessNotification(_localizationService.GetResource("Admin.Plugins.Saved"));

            return Configure();
        }

        #endregion
    }
}

src/Plugins/Nop.Plugin.Shipping.UPS/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}

@model Nop.Plugin.Shipping.UPS.Models.UPSShippingModel
@using Nop.Plugin.Shipping.UPS;

<form asp-controller="ShippingUPS" asp-action="Configure" method="post">
    <script>
        $(document).ready(function () {
            $("#PackingType").change(togglePackingType);
            togglePackingType();
        });

        function togglePackingType() {
            var selectedPackingTypeId = $("#PackingType").val();
            if (selectedPackingTypeId == @(((int)PackingType.PackByDimensions).ToString())) {
                $('#pnlPassDimensions').show();
                $('#pnlPackingPackageVolume').hide();
            }
            else if (selectedPackingTypeId == @(((int)PackingType.PackByOneItemPerPackage).ToString())) {
                $('#pnlPassDimensions').hide();
                $('#pnlPackingPackageVolume').hide();
            }
            else if (selectedPackingTypeId == @(((int)PackingType.PackByVolume).ToString())) {
                $('#pnlPassDimensions').hide();
                $('#pnlPackingPackageVolume').show();
            }
        }
    </script>

    <div class="panel-group">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="Url" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Url" />
                        <span asp-validation-for="Url"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="AccountNumber" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AccountNumber" />
                        <span asp-validation-for="AccountNumber"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="AccessKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AccessKey" />
                        <span asp-validation-for="AccessKey"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="Username" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Username" />
                        <span asp-validation-for="Username"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="Password" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Password" />
                        <span asp-validation-for="Password"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="CustomerClassification" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="CustomerClassification" asp-items="Model.AvailableCustomerClassifications" />
                        <span asp-validation-for="CustomerClassification"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="PickupType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PickupType" asp-items="Model.AvailablePickupTypes" />
                        <span asp-validation-for="PickupType"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="PackagingType" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PackagingType" asp-items="Model.AvailablePackagingTypes" />
                        <span asp-validation-for="PackagingType"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="InsurePackage" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="InsurePackage" />
                        <span asp-validation-for="InsurePackage"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="AdditionalHandlingCharge" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="AdditionalHandlingCharge" />
                        <span asp-validation-for="AdditionalHandlingCharge"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="AvailableCarrierServices" />
                    </div>
                    <div class="col-md-9">
                        @foreach (var csd in Model.AvailableCarrierServices)
                        {
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="CheckedCarrierServices" value="@(csd)" checked="@Model.CarrierServicesOffered.Contains(csd)" />
                                    @csd
                                </label>
                            </div>
                        }
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="PackingTypeValues" />
                    </div>
                    <div class="col-md-9">
                        <nop-select asp-for="PackingType" asp-items="Model.PackingTypeValues" />
                    </div>
                </div>
                <div class="form-group" id="pnlPassDimensions">
                    <div class="col-md-3">
                        <nop-label asp-for="PassDimensions" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PassDimensions" />
                        <span asp-validation-for="PassDimensions"></span>
                    </div>
                </div>
                <div class="form-group" id="pnlPackingPackageVolume">
                    <div class="col-md-3">
                        <nop-label asp-for="PackingPackageVolume" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PackingPackageVolume" />
                        <span asp-validation-for="PackingPackageVolume"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-3">
                        <nop-label asp-for="Tracing" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="Tracing" />
                        <span asp-validation-for="Tracing"></span>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-blue" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>